version: '2'
services:
    invictus-app:
        image: invictus
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://invictus-mysql:3306/invictus?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=invictus-elasticsearch:9300
        ports:
            - 8087:8087
    invictus-mysql:
        extends:
            file: mysql.yml
            service: invictus-mysql
    invictus-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: invictus-elasticsearch
